import math
import time

import PIL
import numpy as np
from PIL import Image
from numpy.ma.core import arctan

from realsense_camera.realsense_camera import RealsenseCamera
from robot_arm import eye2arm_transform
from robot_arm.arm_controller import ArmController
from vlm import image_utils
from vlm.image_utils import mask_diff, center_of_mask
from vlm.lang_sam_demo import show_masks_on_image
from vlm.vision_model import VisionModel


class Jarvis:
    def __init__(self):
        self.arm_controller = ArmController()
        self.arm_state = "horizontal"
        print("Loading vision model...")
        self.vision_model = VisionModel()
        print("Loading realsense camera...")
        self.realsense_camera = RealsenseCamera()
        self.grasp_pose = {
            "black cup": [28, 90],
            "red cup": [28, 90],
            "yellow cup": [22.5, 90],
            "silver cup": [28, 90],
            "teapot": [80.0, 110],
        }

    def detect(self, text_prompt: str):
        # distance between camera and object
        distance = 0.0
        # center coordinate of the surface of the object
        x, y = 0, 0
        # count the times of invalid detect
        # RealSense camera will return 0 when the depth is invalid (undetectable/too far/too near)
        invalid_count, invalid_threshold = 0, 4

        color_image, depth_intrin, depth_image, depth_frame = [None] * 4
        objects_position = []
        while invalid_count < invalid_threshold and distance == 0.0:
            objects_position.clear()
            color_image, depth_image, depth_intrin, depth_frame = self.realsense_camera.get_aligned_images()
            masks = self.vision_model.segment(PIL.Image.fromarray(color_image), text_prompt)
            show_masks_on_image(color_image, masks)
            for i, (y, x) in enumerate(image_utils.center_of_mask(masks)):
                distance = self.realsense_camera.get_pixel_distance(x, y, depth_frame)
                if distance:
                    objects_position.append((x, y, distance, masks[i]))
            if objects_position:
                break
            else:
                print("Invalid frame. Try again.")
                invalid_count += 1

        if invalid_threshold == invalid_count:
            distance = self.realsense_camera.try_get_object_distance(x, y, depth_frame)
            if not distance:
                print("Unable to grasp target object.")
                return []

        return objects_position, color_image, depth_image, depth_intrin, depth_frame

    def pixel_to_3d(self, x, y, distance, depth_intrin, text_prompt):
        """
        Grasp target object by text prompt.
        :param x: x coordinate of center of object surface
        :param y: y coordinate of center of object surface
        :param distance: distance of (x, y) and deep camera
        :param depth_intrin: depth camera intrinsics
        :param text_prompt: text prompt of the grasp target object
        :return:
            - end_pose: end pose to grasp target object
            - target_index: 3D coordinate of target object
        """
        self.arm_controller.set_grip_degree(70)
        px, py, pz, Rx, Ry, Rz = self.arm_controller.end_pose_state()
        T_c = RealsenseCamera.get_coordinate_3d(x, y, distance, depth_intrin) + [1]
        R_g = eye2arm_transform.euler2quaternion([Rx, Ry, Rz])
        T_g = eye2arm_transform.mm2m([px, py, pz])
        target_index = eye2arm_transform.get_target_index(R_g, T_g, T_c).tolist()
        target_index = eye2arm_transform.m2mm(target_index)
        print(f"Position of #{text_prompt}# = {target_index} (mm)")
        # should be generated by some of Grasp Network
        # but here we temporarily use a dict
        grasp = self.grasp_pose[text_prompt]
        end_pose = self.end_pose_transform(*target_index, *grasp)
        return end_pose, target_index

    def end_pose_transform(self, x, y, z, distance, theta):
        """
        Transform detected point to end pose to grasp it.
        :param x: x coordinate of target position
        :param y: y coordinate of target position
        :param z: z coordinate of target position
        :param distance: distance of surface to grasp point
        :param theta: vertical angle of grasp pose
        :return: end pose to grasp target object
        """
        # You may find it like magic.
        # Yes, indeed. math is just like magic. \【T】/
        Rx, Ry, Rz = 0, theta, math.degrees(float(arctan(y / x)))
        theta = math.radians(theta)
        l, r = self.arm_controller.hand_length, self.arm_controller.arm_radius
        mult_factor = (distance - l) * math.sin(theta) / math.sqrt(math.pow(x, 2) + math.pow(y, 2))
        x_e = (1 + mult_factor) * x
        y_e = (1 + mult_factor) * y
        z_e = z + (distance - l) * math.cos(theta) + (r / math.sin(theta))

        return x_e, y_e, z_e, Rx, Ry, Rz

    def set_zero(self):
        self.arm_controller.set_zero_state()
        time.sleep(1)


if __name__ == '__main__':
    jarvis = Jarvis()
    jarvis.arm_controller.lift(100)
    time.sleep(2)
    jarvis.arm_controller.lift(-100)
    time.sleep(2)
    jarvis.arm_controller.set_grip_degree(80)
    time.sleep(1)
    jarvis.arm_controller.lift(100)
    time.sleep(1)
    jarvis.set_zero()