import time

from realsense_camera.realsense_camera import RealsenseCamera
from robot_arm import eye2arm_transform
from robot_arm.arm_controller import ArmController
from vlm import image_utils
from vlm.lang_sam_demo import show_masks_on_image
from vlm.vision_model import VisionModel


class Jarvis:
    def __init__(self):
        self.arm_controller = ArmController()
        self.arm_state = "horizontal"
        self.vision_model = VisionModel()
        self.realsense_camera = RealsenseCamera()
        self.grasp_pose = {
            "black cup": [-110, 190, 0, 90, 0],
            "red cup": [-110, 190, 0, 90, 0],
            "teapot": [-60, 215, 0, 110, 0],
        }

    def grasp(self, text_prompt: str):
        self.arm_controller.set_zero_state()
        # distance between camera and object
        distance = 0.0
        # center coordinate of the surface of the object
        x, y = 0, 0
        # count the times of invalid detect
        # RealSense camera will return 0 when the depth is invalid (undetectable/too far/too near)
        invalid_count, invalid_threshold = 0, 4

        depth_intrin, depth_frame = None, None
        while invalid_count < invalid_threshold and distance == 0.0:
            color_image, depth_image, depth_intrin, color_frames, depth_frame = self.realsense_camera.get_aligned_images()
            masks = self.vision_model.segment(color_image, text_prompt)
            show_masks_on_image(color_image, masks)
            y, x = image_utils.center_of_mask(masks)[0]
            distance = self.realsense_camera.get_pixel_distance(x, y, depth_frame)
            if distance:
                print(f"Distance of #{text_prompt} = {distance} meter.")
                break
            else:
                print("Invalid frame. Try again.")
                invalid_count += 1

        if invalid_threshold == invalid_count:
            distance = self.realsense_camera.try_get_object_distance(x, y, depth_frame)
            if not distance:
                print("Unable to grasp target object.")
                return

        self.arm_controller.set_grip_degree(70)
        px, py, pz, Rx, Ry, Rz = self.arm_controller.end_pose_state()
        T_c = self.realsense_camera.get_coordinate_3d(x, y, distance, depth_intrin) + [1]
        R_g = eye2arm_transform.euler2quaternion([Rx, Ry, Rz])
        T_g = eye2arm_transform.mm2m([px, py, pz])
        target_index = eye2arm_transform.get_target_index(R_g, T_g, T_c).tolist()
        print("target_index:", target_index)
        target_index = eye2arm_transform.m2mm(target_index)
        # should be generated by some of Grasp Network
        # but here we temporarily use a dict
        grasp_pose = self.grasp_pose[text_prompt]
        print("grasp_pose:", grasp_pose)
        target_index[0] += grasp_pose[0]
        target_index[2] = grasp_pose[1]
        self.arm_controller.end_pose_control(target_index + [Rx, Ry, Rz])
        self.arm_controller.set_grip_degree(0)
        time.sleep(1)

    def lift_up(self, height):
        x, y, z, Rx, Ry, Rz = self.arm_controller.end_pose_state()
        if self.arm_state == "horizontal":
            z += height
        elif self.arm_state == "vertical":
            x -= height
        self.arm_controller.end_pose_control([x, y, z, Rx, Ry, Rz])

    def set_zero(self):
        if self.arm_state == "horizontal":
            self.lift_up(10)
        self.arm_controller.set_zero_state()


if __name__ == '__main__':
    jarvis = Jarvis()
    jarvis.set_zero()
    text_prompt = "teapot"
    jarvis.grasp(text_prompt)
    height = 70
    jarvis.lift_up(height)
    time.sleep(0.5)
    x, y, z, Rx, Ry, Rz = jarvis.arm_controller.end_pose_state()
    x += 70
    jarvis.arm_controller.end_pose_control([x, y, z, Rx, Ry, Rz])
    time.sleep(0.5)
    x -= 70
    jarvis.arm_controller.end_pose_control([x, y, z, Rx, Ry, Rz])
    jarvis.lift_up(-height)
    time.sleep(1)
    jarvis.arm_controller.set_grip_degree(80)
    time.sleep(0.5)
    jarvis.lift_up(height)
    jarvis.set_zero()
