import math
import time

from numpy.ma.core import arctan

from realsense_camera.realsense_camera import RealsenseCamera
from robot_arm import eye2arm_transform
from robot_arm.arm_controller import ArmController
from vlm import image_utils
from vlm.lang_sam_demo import show_masks_on_image
from vlm.vision_model import VisionModel


class Jarvis:
    def __init__(self):
        self.arm_controller = ArmController()
        self.arm_state = "horizontal"
        print("Loading vision model...")
        self.vision_model = VisionModel()
        print("Loading realsense camera...")
        self.realsense_camera = RealsenseCamera()
        self.grasp_pose = {
            "black cup": [28, 90],
            "red cup on left": [28, 90],
            "yellow cup on left": [22.5, 90],
            "white cup on left": [28, 90],
            "black cup on left": [28, 90],
            "teapot": [80.0, 100],
        }

    def detect(self, text_prompt: str):
        # distance between camera and object
        distance = 0.0
        # center coordinate of the surface of the object
        x, y = 0, 0
        # count the times of invalid detect
        # RealSense camera will return 0 when the depth is invalid (undetectable/too far/too near)
        invalid_count, invalid_threshold = 0, 4

        depth_intrin, depth_frame = None, None
        objects_position = []
        while invalid_count < invalid_threshold and distance == 0.0:
            objects_position.clear()
            color_image, depth_image, depth_intrin, color_frames, depth_frame = self.realsense_camera.get_aligned_images()
            masks = self.vision_model.segment(color_image, text_prompt)
            show_masks_on_image(color_image, masks)
            for i, (x, y) in enumerate(image_utils.center_of_mask(masks)):
                distance = self.realsense_camera.get_pixel_distance(x, y, depth_frame)
                if distance:
                    objects_position.append((x, y, distance))
            if objects_position:
                break
            else:
                print("Invalid frame. Try again.")
                invalid_count += 1

        if invalid_threshold == invalid_count:
            distance = self.realsense_camera.try_get_object_distance(x, y, depth_frame)
            if not distance:
                print("Unable to grasp target object.")
                return []

        return objects_position, depth_intrin

    def grasp(self, x, y, distance, depth_intrin, text_prompt):
        """
        Grasp target object by text prompt.
        :param x: x coordinate of center of object surface
        :param y: y coordinate of center of object surface
        :param distance: distance of (x, y) and deep camera
        :return: True if grasp else False
        """
        self.arm_controller.set_grip_degree(70)
        px, py, pz, Rx, Ry, Rz = self.arm_controller.end_pose_state()
        T_c = RealsenseCamera.get_coordinate_3d(x, y, distance, depth_intrin) + [1]
        R_g = eye2arm_transform.euler2quaternion([Rx, Ry, Rz])
        T_g = eye2arm_transform.mm2m([px, py, pz])
        target_index = eye2arm_transform.get_target_index(R_g, T_g, T_c).tolist()
        print("Target index = ", target_index)
        target_index = eye2arm_transform.m2mm(target_index)

        # should be generated by some of Grasp Network
        # but here we temporarily use a dict
        grasp = self.grasp_pose[text_prompt]
        end_pose = self.end_pose_transform(*target_index, *grasp)
        print("End pose = ", end_pose)
        flag = self.arm_controller.end_pose_control(list(end_pose))
        if not flag:
            print("Segment may be failed, or object is unreachable. Please check again.")
            return False

        self.arm_controller.set_grip_degree(70)
        time.sleep(0.5)
        self.arm_controller.set_grip_degree(0)
        return True

    def end_pose_transform(self, x, y, z, distance, theta):
        """
        Transform detected point to end pose to grasp it.
        :param x: x coordinate of target position
        :param y: y coordinate of target position
        :param z: z coordinate of target position
        :param distance: distance of surface to grasp point
        :param theta: vertical angle of grasp pose
        :return: end pose to grasp target object
        """
        # You may find it like magic.
        # Yes, indeed. math is just like magic. \【T】/
        Rx, Ry, Rz = 0, theta, math.degrees(float(arctan(y / x)))
        theta = math.radians(theta)
        l, r = self.arm_controller.hand_length, self.arm_controller.arm_radius
        mult_factor = (distance - l) * math.sin(theta) / math.sqrt(math.pow(x, 2) + math.pow(y, 2))
        x_e = (1 + mult_factor) * x
        y_e = (1 + mult_factor) * y
        z_e = z + (distance - l) * math.cos(theta) + (r / math.sin(theta))

        return x_e, y_e, z_e, Rx, Ry, Rz

    def set_zero(self):
        self.arm_controller.set_zero_state()
        time.sleep(1)


if __name__ == '__main__':
    jarvis = Jarvis()
    # jarvis.set_zero()
    jarvis.arm_controller.end_pose_control(jarvis.arm_controller.init_end_pose)
    # pos = [45, 10, -35, 0, 60, 0]
    pos = [35, 10, -35, 0, 60, 0]
    jarvis.arm_controller.joint_control(pos)
    time.sleep(1)
    prompt = "white cup on left"
    obj_lst, depth_intrin = jarvis.detect(prompt)
    xe, ye, dis = obj_lst[0]
    time.sleep(1)
    # pos = [40, 10, -35, 0, 30, 0]
    # jarvis.arm_controller.joint_control(pos)
    # jarvis.set_zero()
    time.sleep(1)
    jarvis.grasp(xe, ye, dis, depth_intrin, prompt)
    jarvis.arm_controller.lift(100)
    time.sleep(2)
    jarvis.arm_controller.lift(-100)
    time.sleep(2)
    jarvis.arm_controller.set_grip_degree(80)
    time.sleep(1)
    jarvis.arm_controller.lift(100)
    time.sleep(1)
    jarvis.set_zero()